apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-wiremock-server-demo
  labels:
    app: sample-wiremock-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-wiremock-server
  template:
    metadata:
      labels:
        app: sample-wiremock-server
    spec:
      containers:
        - name: sample-wiremock-server
          image: cgpradeepkumar/sample-wiremock-server
          ports:
            - containerPort: 8080
